version: '2'

networks:
  intranet:
    external: true

services:
  haproxy:
    restart: unless-stopped
    image: haproxy
    container_name: haproxy
    ports:
      - 80:80
    networks:
      intranet:
        ipv4_address: 172.20.0.2
    volumes:
      - /var/docker/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

  postgres:
    restart: unless-stopped
    image: postgres:13
    container_name: postgres
    networks:
      intranet:
        ipv4_address: 172.20.0.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pifagor
    volumes:
      - /var/docker/postgres/data:/var/lib/postgresql/data
      - /var/docker/postgres/temp:/var/lib/postgresql/temp

  jira01:
    restart: unless-stopped
    image: registry.bvn.me/slava/jira-server-dev:8.5.8
    container_name: jira01
    networks:
      intranet:
        ipv4_address: 172.20.0.4
    hostname: jira01
    extra_hosts:
        - "jira02:172.20.0.14"
        - "jira03:172.20.0.24"
    depends_on:
      - postgres
    environment:
      ATL_PROXY_NAME: docker.home
      ATL_TOMCAT_PORT: 8080
      ATL_PROXY_PORT: 80
      ATL_TOMCAT_SCHEME: http
      ATL_TOMCAT_SECURE: "false"
      ATL_TOMCAT_CONTEXTPATH: /jira
      ATL_DB_TYPE: postgresql
      ATL_JDBC_URL: jdbc:postgresql://postgres:5432/jira
      ATL_JDBC_USER: jira_user
      ATL_JDBC_PASSWORD: pifagor
      JVM_SUPPORT_RECOMMENDED_ARGS: -Xms8192m -Xmx8192m -XX:+UseG1GC
    volumes:
      - /var/docker/jira.node01:/var/atlassian/application-data/jira
      - /var/docker/jira.shared:/var/atlassian/application-data/jira-shared

  confluence:
    restart: unless-stopped
    image: registry.bvn.me/slava/confluence-server-dev:7.4.4
    container_name: confluence
    networks:
      intranet:
        ipv4_address: 172.20.0.5
    depends_on:
      - postgres
    environment:
      ATL_PROXY_NAME: docker.home
      ATL_TOMCAT_PORT: 8090
      ATL_PROXY_PORT: 80
      ATL_TOMCAT_SCHEME: http
      ATL_TOMCAT_SECURE: "false"
      ATL_TOMCAT_CONTEXTPATH: /confluence
      ATL_DB_TYPE: postgresql
      ATL_JDBC_URL: jdbc:postgresql://postgres:5432/confdb
      ATL_JDBC_USER: confdb_user
      ATL_JDBC_PASSWORD: pifagor
      JVM_SUPPORT_RECOMMENDED_ARGS: -Xms4096m -Xmx4096m -XX:+UseG1GC
    volumes:
      - /var/docker/confluence:/var/atlassian/application-data/confluence
